Build: Remove max perm size option gradle jvmargs from gradle properties
This 'MaxPermSize' JVM argument was added back in 2016 (July) and as
part of this starting 780ed5dfdfee96f0466068b232966fc0012c87bc commit.
By now, and with newer versions of Java (see Java 17), this argument has
been effectively removed. As such, when engineers are trying to build
this project with JDK17, they can't, see below exception:

------------------------------------------------------------------------

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at
https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html
Process command line: /opt/homebrew/Cellar/openjdk@17/17.0.5/...
Please read the following process output to find out more:
-----------------------
Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

------------------------------------------------------------------------

FYI: This JVM argument went obsolete as part of Java 16 and then
completely removed as part of Java 17, see below:

- Java 16: https://docs.oracle.com/en/java/javase/16/docs/specs/man/
java.html#obsolete-java-options
- Java 17: https://docs.oracle.com/en/java/javase/17/docs/specs/man/
java.html#removed-java-options