Deps: Update robolectric to 4.9
This is done because otherwise the 'testDebugUnitTest' task fails the
test, when run on command line, with the below 'ClassNotFoundException'
error:

------------------------------------------------------------------------

java.lang.NoClassDefFoundError: android/content/ContentResolver
...
Caused by: java.lang.ClassNotFoundException:
couldn't load android.content.ContentResolver
...
Caused by: java.lang.IllegalArgumentException:
Unsupported class file major version 61"

------------------------------------------------------------------------

Release Link: https://github.com/robolectric/robolectric/releases/tag/
robolectric-4.9